### ISSUE TITLE
go template : automaticly pass vars with infos like recipe and repository

### ISSUE THREAD

**Issue by loic-roux-404** [manala/manala#25]
To avoid repeating information like repository and recipe name each time we create a new manala template file,  it can be useful to find a system to keep these in templates like `.manala.yaml.tpml`.

Example in context (file : .manala.yml.tmpl)

```goyaml
manala:
  repository: {{ .manala.repository }} 
  recipe: {{ .manala.recipe }}

```

Another usage

```goyaml
{{ .manala | toYaml }}
```

For now i can workaround this by adding a variable `recipe_save` in my recipe file : 

```yaml
manala:
    description: Python
    sync:
      - .vscode/
      - ../ops.vagrant/.manala/ .manala/vg-facade
      - ../ops.vagrant/.manala.yaml.tmpl .manala.yaml.tmpl
      - ../ops.vagrant/Vagrantfile Vagrantfile
      - .gitignore.tmpl .gitignore
      - .manala/python.mk
      - .editorconfig
      - .flake8
      - ../.gitattributes .gitattributes

# Save variable (manala delete original config vars under manala key)
recipe_save: dev.python
```

I would be happy to submit a PR if you find this enhancement ok 😀
