### ISSUE TITLE
bug : look like manala can't create recursively folders when calling file from siblings

### ISSUE THREAD

**Issue by loic-roux-404** [manala/manala#26]
It's a special case.

### on recipe side

```yaml
manala:
    description: Python
    sync:
      - ../.manala.yaml.tmpl.dist .manala.yaml.tmpl.dist
      # CI / CD
      - .manala/tests/
      - ../.github/workflows/auto-merge.yml .github/workflows/
```

### project side

```sh
manala init --repository=/Users/loic/Ops/manala-recipes                                            
   • Synced file               path=.manala.yaml
   • Synced directory          path=.manala/tests
   ⨯ open .github/workflows: no such file or directory
```

Also with a single file (previous case was a sub folder)

```sh
manala init --repository=/Users/loic/Ops/manala-recipes                                              
   • Synced file               path=.manala.yaml
   ⨯ open .github/PULL_REQUEST_TEMPLATE.md: no such file or directory
```

Capture of all y retries : 

> I had created the folder `.github` fixing this error, it's a workaround for now

<img width="1156" alt="Screenshot 2021-03-02 at 23 34 26" src="https://user-images.githubusercontent.com/47380500/109724440-dc45fe80-7baf-11eb-8f9e-5ee6537a56d0.png">

**Comment by nervo** [comment]
Ok, could you try like this ?

```
manala:
    description: Python
    sync:
      # "../" is implicit, you don't nee to prefix each entry
      # also, second parameter is useless, it's defaulted to the same name/directory file, removing tmlp and dist extensions
      - .manala.yaml.tmpl.dist
      # you don't need trailing slash for directories, but it should work with :)
      - .manala/tests
      # try to promote ""yaml" extension instead of "yml" :)
      - .github/workflows/auto-merge.yml
```
